apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app-namespace
spec:
  type: ExternalName
  externalName: usermgmtdb.closcimyuuq0.ap-south-1.rds.amazonaws.com

---

apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-service
  namespace: app-namespace
  labels: 
    app: usermgmt-restapp
spec:
  type: NodePort
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 8095
      targetPort: 8095
      nodePort: 31231

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: smtp-service
# spec:
#   type: ExternalName
#   externalName: email-smtp.us-east-1.amazonaws.com

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: notification-clusterip-service
#   labels:
#     app: notification-restapp
# spec:
#   type: ClusterIP
#   selector:
#     app: notification-restapp
#   ports:
#   - port: 8096
#     targetPort: 8096

---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-nodeport-service
  labels:
    app: app1-nginx
  annotations:
#Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
#    alb.ingress.kubernetes.io/healthcheck-path: /app1/index.html
spec:
  type: NodePort
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80