apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  namespace: app-namespace
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:  
    metadata:
      labels: 
        app: usermgmt-restapp
    spec:
      serviceAccountName: ums-pod-identity-deployment-sa
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: usermgmt-restapp
          image: 829007908826.dkr.ecr.ap-south-1.amazonaws.com/eks/ums:1.0.0  
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: ums-mysql-rds-secrets-k8s
                  key: DB_HOSTNAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ums-mysql-rds-secrets-k8s
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ums-mysql-rds-secrets-k8s
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ums-mysql-rds-secrets-k8s
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ums-mysql-rds-secrets-k8s
                  key: DB_PASSWORD
            # - name: NOTIFICATION_SERVICE_HOST
            #   value: "notification-clusterip-service"
            # - name: NOTIFICATION_SERVICE_PORT
            #   value: "8096"           
          livenessProbe:
            exec:
              command: 
                - /bin/sh
                - -c 
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "ums-mysql-rds-secrets"

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: notification-microservice
#   labels:
#     app: notification-restapp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: notification-restapp
#   template:
#     metadata:
#       labels:
#         app: notification-restapp
#     spec:
#       containers:
#         - name: notification-service
#           image: 829007908826.dkr.ecr.ap-south-1.amazonaws.com/eks/notifications-microservice:1.0.0
#           ports:
#             - containerPort: 8096
#           imagePullPolicy: Always
#           env:
#             - name: AWS_MAIL_SERVER_HOST
#               value: "smtp-service"
#             - name: AWS_MAIL_SERVER_USERNAME
#               value: "AKIASUF7HC7SQJ6BCLVS"
#             - name: AWS_MAIL_SERVER_PASSWORD
#               value: "BARcmLiC68wgmhTy/cQvz/E8vFzeizGqdeASNtCs6+Nv"
#             - name: AWS_MAIL_SERVER_FROM_ADDRESS
#               value: "sydport11@gmail.com"