apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ums-mysql-secrets
  namespace: app-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "eks/ums/mysql"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_HOSTNAME"
            objectAlias: "hostname"
          - path: "DB_PORT"
            objectAlias: "port"
          - path: "DB_NAME"
            objectAlias: "dbname"
          - path: "DB_USERNAME"
            objectAlias: "username"
          - path: "DB_PASSWORD"
            objectAlias: "password"
    usePodIdentity: "true"
  secretObjects:
    - secretName: ums-mysql-secrets-k8s
      type: Opaque
      data:
        - objectName: hostname
          key: DB_HOSTNAME
        - objectName: port
          key: DB_PORT
        - objectName: dbname
          key: DB_NAME
        - objectName: username
          key: DB_USERNAME
        - objectName: password
          key: DB_PASSWORD